# docker-compose.yml
services:
    mongo:
        image: mongo:7.0
        container_name: mongo-ipssi
        restart: always
        ports: ["27017:27017"]
        volumes: ["mongo-data:/data/db"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: ipssi2025
    mongo-express:
        image: mongo-express:latest
        ports: ["8081:8081"]
        depends_on: [mongo]
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: ipssi2025
volumes:
    mongo-data: {}